behaviors:
  HandBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 16384
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    max_steps: 100000
    keep_checkpoints: 5
    checkpoint_interval: 2000
    time_horizon: 512
    summary_freq: 1000
    threaded: true
environment_parameters:
  weight_distance: 1.0
  weight_rotation: 0.5
  frames_per_episode:
    curriculum:
    - name: Lesson0
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 0.3
      value: 1
    - name: Lesson1
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 0.6
      value: 10
    - name: Lesson2
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 1.0
      value: 100
  steps_per_one_frame:
    curriculum:
    - name: Lesson0
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 0.3
      value: 100
    - name: Lesson1
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 0.6
      value: 10
    - name: Lesson2
      completion_criteria:
        measure: progress
        behavior: HandBehavior
        threshold: 1.0
      value: 1
