services:
  python:
    build: ../python
    container_name: python
    restart: always
    tty: true
    ports:
      - "5004:5004"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - ../app/results:/app/results
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ../app/db:/data/db
      - ../app/configdb:/data/configdb
